server:
  host: "0.0.0.0"
  port: "8080"
  mode: "release" # debug | release

database:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: ""
  name: "panflow"

redis:
  host: "127.0.0.1"
  port: "6379"
  password: ""
  db: 0

log:
  level: "info" # debug | info | warn | error

panflow:
  admin_password: ""
  parse_password: ""
  jwt_secret: "panflow-change-me"
  jwt_expire_hours: 24
  debug: false
  save_histories_day: 7

  # 解析
  guest_user_agent: "netdisk;P2SP;3.0.20.138"

  # 全局代理（可选）
  proxy_http: ""

  # 邮件（可选）
  mail_switch: false
  mail_host: "smtp.example.com"
  mail_port: 465
  mail_username: ""
  mail_password: ""
  mail_from_address: ""
  mail_from_name: "PanFlow"
  mail_to_address: ""
  mail_to_name: ""
